name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Get dependencies
        run: go mod download

      - name: Set permissions
        run: chmod +x build-all.sh

      - name: Build
        run: ./build-all.sh

      - name: Create Release
        run: ls -la ./build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/*